 name: Create Git Tag And Release Note
 
 on:
   push:
     branches:
       - main
 
 jobs:
   create-git-tag:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Create Release Tag
         id: create_release_tag
         run: |
           echo 1.28.2 > TAG_NUM
           echo v$(cat TAG_NUM) > TAG_NAME
           echo "TAG_NAME=$(cat TAG_NAME)" >> $GITHUB_ENV
           git tag $(cat TAG_NAME)
           git push -f origin $(cat TAG_NAME)
       - name: Set current datetime as env variable
         env:
           TZ: "Asia/Tokyo" # タイムゾーン指定
         run: echo "CURRENT_DATETIME=$(date +'%Y年%m月%d日 %H:%M頃')" >> $GITHUB_ENV
       - name: Create Body
         run: |
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "# ストアリリース日時<<$EOF" >> temp
           echo "" >> temp
           echo "${{ env.CURRENT_DATETIME }}" >> temp
           echo "BODY=$(cat temp)" >> $GITHUB_ENV
           echo "$EOF" >> $GITHUB_ENV
       - name: Create Release Note
         id: create_release_note
         uses: ncipollo/release-action@v1
         with: 
           tag: ${{ env.TAG_NAME }}
           name: ${{ env.TAG_NAME }}
           body: ${{ env.BODY }}
           generateReleaseNotes: true
           makeLatest: "latest"

